stages:
  - prepare
  - build
  - package

variables:
  MOZCONFIG: "$CI_PROJECT_DIR/mozconfig/release.mozconfig"
  CCACHE_DIR: "$CI_PROJECT_DIR/.ccache"
  RUSTC_WRAPPER: "sccache"

cache:
  key: ccache
  paths:
    - .ccache/

default:
  image: debian:bookworm-slim

before_script:
  # Update packages and install Firefox build deps
  - apt-get update && apt-get install -y git curl wget python3 python3-pip unzip zip \
    build-essential autoconf2.13 clang llvm lld nodejs npm yasm \
    libgtk-3-dev libdbus-glib-1-dev libxt-dev libpulse-dev \
    libasound2-dev libx11-xcb-dev libxrender-dev libxcomposite-dev \
    libxdamage-dev libxrandr-dev libxi-dev libfreetype6-dev \
    libfontconfig1-dev libglib2.0-dev libpango1.0-dev libcairo2-dev \
    ccache sccache

prepare:
  stage: prepare
  script:
    - bash bootstrap_fork.sh
  artifacts:
    paths:
      - upstream
      - mozconfig
      - patches
      - policies
      - browser/branding
    expire_in: 1 week

build:
  stage: build
  script:
    - cd upstream
    - git checkout main
    - cd ..
    - git apply patches/*.patch || true
    - ./upstream/mach bootstrap --application-choice browser --no-interactive
    - ./upstream/mach build -v
  artifacts:
    paths:
      - upstream/obj-*/dist/bin/
    expire_in: 1 week

package:
  stage: package
  script:
    - cd upstream/obj-*/dist
    - tar -czf "$CI_PROJECT_DIR/${CI_PROJECT_NAME}-linux.tar.gz" bin/*
  artifacts:
    paths:
      - "${CI_PROJECT_NAME}-linux.tar.gz"
    expire_in: 2 weeks
